### ISSUE TITLE
Unable to build from foafProfile shape

### ISSUE THREAD

**Issue by lurnid** [jaxoncreed/ldo-react-tutorial-1#1]
When I run `npm run build:ldo` (in step 3 of the tutorial), I get this error:

```
/Users/lurnid/code/projects/iopa/solid-test-apps/dapsi-solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorParentSubTraverser.js:57
            subTraverser = subTraversers[traverserDefinition[itemTypeName].kind];
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at /path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorParentSubTraverser.js:57:76
    at step (/path/to/solid-solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorParentSubTraverser.js:33:23)
    at Object.next (/path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorParentSubTraverser.js:14:53)
    at /path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorParentSubTraverser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorParentSubTraverser.js:4:12)
    at visitorParentSubTraverser (/path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorParentSubTraverser.js:49:12)
    at /path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorUnionSubTraverser.js:53:87
    at step (/path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorUnionSubTraverser.js:33:23)
    at Object.next (/path/to/solid-app/node_modules/type-traverser/dist/visitorSubTraversers/VisitorUnionSubTraverser.js:14:53)
```

Running node v16.13.1 & npm 8.17.0

**Comment by jaxoncreed** [comment]
Turns out it was a dependency problem. One of the dependencies had breaking update, but only changed its minor version. I've corrected it now. So, if you upgrade to ldo-cli v0.1.3 the build should work.
